/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.dialogos;
import fes.aragon.mysql.Conexion;
import fes.aragon.dao.DespachoDAO;
import fes.aragon.dao.ProfesorDAO;
import fes.aragon.modelo.TablaProfesor;
import fes.aragon.pojo.Despacho;
import fes.aragon.pojo.Profesor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Frank
 */
public class CRUDProfesor extends javax.swing.JDialog {
    private DefaultComboBoxModel ModeloDespacho= new DefaultComboBoxModel();
    private TablaProfesor modeloTabla= new TablaProfesor();

    /**
     * Creates new form CRUDProfesor
     */
    public CRUDProfesor(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        iniciarComponentes();
         this.setLocationRelativeTo(null);
    }
    private void iniciarComponentes() throws SQLException{
        try {
            DespachoDAO datos= new DespachoDAO();
            ArrayList<Despacho> despacho= new ArrayList<>();
            ModeloDespacho.addElement("Escoje un despacho");
            despacho=datos.obtenerDespacho();
            for (Despacho desp : despacho) {
                ModeloDespacho.addElement(desp);   
            }
            ProfesorDAO profesor=new ProfesorDAO();
            modeloTabla.setModeloDespacho(ModeloDespacho);
            modeloTabla.setDatos(profesor.BuscarProfesor());
            modeloTabla.fireTableDataChanged();
            
      
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error en la base de datos");
        } catch (SQLException ex) {
            ex.printStackTrace();
           JOptionPane.showMessageDialog(rootPane, "Error en la base de datos");
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(this.modeloTabla);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("CURP");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIMO PATERNO");

        jLabel4.setText("APELLIDO MATERNO");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("DESPACHO");

        jComboBox1.setModel(this.ModeloDespacho);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(jTextField3)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(325, 325, 325)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(414, 414, 414))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
   
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            ProfesorDAO alm= new ProfesorDAO();
            Profesor tmp=this.evaluarCamposAlmacenar();
            if(tmp!=null){
             alm.insertar(tmp);   
             modeloTabla.getDatos().clear();
             alm = new ProfesorDAO();
             modeloTabla.setDatos(alm.BuscarProfesor());
             modeloTabla.fireTableDataChanged();
             this.limpiar();
            }   
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
               JOptionPane.showConfirmDialog(rootPane, "Error de la base de datos");
        } catch (SQLException ex) {
            ex.printStackTrace();
               JOptionPane.showConfirmDialog(rootPane, "Error de la base de datos");
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (modeloTabla.getDatos().size() > 0){
            Profesor tmp=modeloTabla.getDatos().get(this.jTable1.getSelectedRow());
            this.jTextField1.setText(tmp.getCurp());
            this.jTextField2.setText(tmp.getNombre());
            this.jTextField3.setText(tmp.getAp_paterno());
            this.jTextField4.setText(tmp.getAp_materno());
            for (int i = 1; i < ModeloDespacho.getSize(); i++) {
                Despacho temp=(Despacho)ModeloDespacho.getElementAt(i);
                if(tmp.getId_despacho()==temp.getId_despacho()){
                    this.jComboBox1.setSelectedIndex(i);
                    break;
                }
                
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            ProfesorDAO alm= new ProfesorDAO();
            Profesor tmp=this.evaluarCamposModificar();
            if(tmp!=null){
             alm.modificar(tmp);   
             modeloTabla.getDatos().clear();
             alm = new ProfesorDAO();
             modeloTabla.setDatos(alm.BuscarProfesor());
             modeloTabla.fireTableDataChanged();
             this.limpiar();
            }   
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
               JOptionPane.showConfirmDialog(rootPane, "Error de la base de datos");
        } catch (SQLException ex) {
            ex.printStackTrace();
               JOptionPane.showConfirmDialog(rootPane, "Error de la base de datos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
 private Profesor evaluarCamposAlmacenar(){
        boolean correcto=true;
        String mensaje = "";
        String valor1= this.jTextField1.getText();
        String valor2= this.jTextField2.getText();
        String valor3= this.jTextField3.getText();
        String valor4= this.jTextField4.getText();
        Profesor datos = new Profesor();
        if (valor1 == null || valor1.isEmpty() || valor1.regionMatches(0," ", 0,1) || valor1.length()>50){
           mensaje+="Escriba un CRUP\n" ;
           correcto=false;  
        } else if (valor2 == null || valor2.isEmpty() || valor2.regionMatches(0," ", 0,1) || valor2.length()>50){
           mensaje+="Escriba un Nombre\n" ;
           correcto=false;  
        }else if (valor3 == null || valor3.isEmpty() || valor3.regionMatches(0," ", 0,1) || valor3.length()>50){
           mensaje+="Escriba un Apellido Paterno\n" ;
           correcto=false;  
        }else if (valor4 == null || valor4.isEmpty() || valor4.regionMatches(0," ", 0,1) || valor4.length()>50){
           mensaje+="Escriba un Apellido materno\n" ;
           correcto=false;  
        }
        if(!correcto){
           JOptionPane.showConfirmDialog(rootPane, mensaje);
           datos = null;
       }else{
            
            datos.setCurp(valor1);
            datos.setNombre(valor2);
            datos.setAp_paterno(valor3);
            datos.setAp_materno(valor4);
            Despacho tmpDespacho =((Despacho) this.jComboBox1.getSelectedItem());
            datos.setId_despacho(tmpDespacho.getId_despacho());
        } 
        return datos;
    }
    private Profesor evaluarCamposModificar(){
        boolean correcto=true;
        String mensaje = "";
        String valor1= this.jTextField1.getText();
        String valor2= this.jTextField2.getText();
        String valor3= this.jTextField3.getText();
        String valor4= this.jTextField4.getText();
        Profesor datos = new Profesor();
        if (valor1 == null || valor1.isEmpty() || valor1.regionMatches(0," ", 0,1) || valor1.length()>50){
           mensaje+="Escriba un CRUP\n" ;
           correcto=false;  
        } else if (valor2 == null || valor2.isEmpty() || valor2.regionMatches(0," ", 0,1) || valor2.length()>50){
           mensaje+="Escriba un Nombre\n" ;
           correcto=false;  
        }else if (valor3 == null || valor3.isEmpty() || valor3.regionMatches(0," ", 0,1) || valor3.length()>50){
           mensaje+="Escriba un Apellido Paterno\n" ;
           correcto=false;  
        }else if (valor4 == null || valor4.isEmpty() || valor4.regionMatches(0," ", 0,1) || valor4.length()>50){
           mensaje+="Escriba un Apellido materno\n" ;
           correcto=false;  
        }
        if(!correcto){
           JOptionPane.showConfirmDialog(rootPane, mensaje);
           datos = null;
       }else{
            Profesor tmp=modeloTabla.getDatos().get(this.jTable1.getSelectedRow());
            if(tmp!=null){
                datos.setId_profesor(tmp.getId_profesor());
            }
            datos.setCurp(valor1);
            datos.setNombre(valor2);
            datos.setAp_paterno(valor3);
            datos.setAp_materno(valor4);
            Despacho tmpDespacho =((Despacho) this.jComboBox1.getSelectedItem());
            datos.setId_despacho(tmpDespacho.getId_despacho());
        } 
        return datos;
    }
    private void limpiar (){
      this.jTextField1.setText("");
      this.jTextField2.setText("");
      this.jTextField3.setText("");
      this.jTextField4.setText("");
      this.jComboBox1.setSelectedIndex(0);
  } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDProfesor dialog = null;
                try {
                    dialog = new CRUDProfesor(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(CRUDProfesor.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
